global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "thumbnailgen"
    static_configs:
      - targets: ["thumbnailgen:8080"]
    metrics_path: "/metrics"
    scrape_interval: 5s
    scrape_timeout: 3s
    honor_labels: true
